import sys

class Alerts:
	  time = '"15min"'
          def __init__(self, topic_name, warning=1000000, critical=3000000, dc="*", env="*"):
                     self.warning = warning
                     self.critical = critical
                     self.topic_name = topic_name
                     self.dc = dc
                     self.env = env
          
          def set_topic_alert(self,file_ptr):
                     entry = "graphite.absolute_threshold('movingAverage(maxSeries(stats." + self.dc + ".migrator." + self.env + "." + self.topic_name + ".kafka_offset_lag.*)," + Alerts.time + ")', alias='migrator_lag_alerts_" + self.topic_name + "', warning_over=" + str(self.warning) + ", critical_over=" + str(self.critical) + ")"
                     print >> file_ptr, entry


alertList = [
Alerts("api_client_signups",),
Alerts("api_client_transactions",),
Alerts("api_created_trips",),
Alerts("api_db_audit_logs",),
Alerts("api_db_nearestcab_logs_client",),
Alerts("api_db_nearestcab_logs_driver",),
Alerts("api_db_sms_logs",),
Alerts("api_driver_signups",),
Alerts("api_driver_status_change",),
Alerts("api_goldeta_accuracy",),
Alerts("api_lib_trips_trip_updator",),
Alerts("api_lost_items",),
Alerts("api_model_document",),
Alerts("api_payment_alipay_data_charge",),
Alerts("api_payment_alipay_data_sign",),
Alerts("api_promotions_apply",),
Alerts("api_signups",),
Alerts("api_trip_create_params_no_gps",),
Alerts("api_trip_update_params",),
Alerts("api_views_driver_devices_dissociations",),
Alerts("artemis_event_emitter_100hz_log",),
Alerts("cerebro_geosurge_recommended_multipliers_v2",),
Alerts("cerebro_multipliers_published",),
Alerts("cleopatra_artemis_data_email",),
Alerts("cleopatra_artemis_data_sms",),
Alerts("cleopatra_event_email",),
Alerts("coral_views_account_invitations",),
Alerts("cream_transactions",),
Alerts("cream_transactions",),
Alerts("dispatch_events",),
Alerts("dispatch_events_client_canceled",),
Alerts("dispatch_events_client_eyeballed",),
Alerts("dispatch_events_destination_set",),
Alerts("dispatch_events_driver_accepted",),
Alerts("dispatch_events_driver_arrived",),
Alerts("dispatch_events_driver_canceled",),
Alerts("dispatch_events_driver_capabilities_updated",),
Alerts("dispatch_events_driver_dispatched",),
Alerts("dispatch_events_driver_expired",),
Alerts("dispatch_events_driver_rated",),
Alerts("dispatch_events_driver_rejected",),
Alerts("dispatch_events_driver_status_changes",),
Alerts("dispatch_events_fare_split_accepted",),
Alerts("dispatch_events_fare_split_invited",),
Alerts("dispatch_events_pickup_requested",),
Alerts("dispatch_events_ridepool_merged",),
Alerts("dispatch_events_surge_multipliers_received",),
Alerts("dispatch_events_trip_began",),
Alerts("dispatch_events_trip_ended",),
Alerts("dispatch_events_trip_sent_to_api",),
Alerts("dispatch_events_trip_shared",),
Alerts("dispatch_events_trip_unfulfilled",),
Alerts("dispatch_events_user_session",),
Alerts("dispatch_failed_signups",),
Alerts("driver_shift_log",),
Alerts("driver_twilio_log",),
Alerts("driver_twilio_log_updates",),
Alerts("ezpzpass_guarantees",),
Alerts("ezpzpass_lib_uberpool_upfront_fare",),
Alerts("ezpzpass_views",),
Alerts("fail_dispatch_events_client_canceled",),
Alerts("fail_dispatch_events_driver_accepted",),
Alerts("fail_dispatch_events_driver_arrived",),
Alerts("fail_dispatch_events_driver_canceled",),
Alerts("fail_dispatch_events_driver_dispatched",),
Alerts("fail_dispatch_events_pickup_requested",),
Alerts("fail_dispatch_events_trip_began",),
Alerts("fail_dispatch_events_trip_ended",),
Alerts("fail_dispatch_events_trip_unfulfilled",),
Alerts("flipr_backend_db_audit_logs",),
Alerts("free-candy_rider_signups",),
Alerts("goldeta_etas",),
Alerts("growth_driver_engagement_events",),
Alerts("growth_gofetch",),
Alerts("growth_gofetch_adjust",),
Alerts("growth_gofetch_adwords",),
Alerts("growth_gofetch_bing",),
Alerts("growth_gofetch_csv_sources",),
Alerts("growth_gofetch_exact_target_events",),
Alerts("growth_gofetch_exact_target_list_membership",),
Alerts("growth_gofetch_exact_target_lists",),
Alerts("growth_gofetch_exact_target_send_jobs",),
Alerts("growth_gofetch_facebook",),
Alerts("growth_gofetch_projections",),
Alerts("growth_gofetch_yahoo",),
Alerts("halyard_events_treatments",),
Alerts("heaven_nginx_access",),
Alerts("hp-chaperone-audit",),
Alerts("hp_demand_job-assigned",),
Alerts("hp_demand_job-canceled",),
Alerts("hp_demand_job-completed",),
Alerts("hp_demand_job-created",),
Alerts("hp_demand_job-destroyed",),
Alerts("hp_demand_job-expired",),
Alerts("hp_demand_job-failed",),
Alerts("hp_demand_job-offered",),
Alerts("hp_demand_job-offer-expired",),
Alerts("hp_demand_job-pickup-arrived",),
Alerts("hp_demand_job-pickup-completed",),
Alerts("hp_demand_job-unassigned",),
Alerts("hp_demand_job-waypoint-location-set",),
Alerts("hp_demand_job-waypoint-status-updated",),
Alerts("hp_optic_client-eyeballed",),
Alerts("hp_optic_client-zeroed",),
Alerts("hp_event_user",),
Alerts("hp_event_user_driver_app",),
Alerts("hp_event_user_driver_app_20pct_sample",),
Alerts("hp_event_user_rider_app_20pct_sample",),
Alerts("hp_event_user_session_driver_app",),
Alerts("hp_event_user_session_rider_app",),
Alerts("hp_event_user_vpl_app",),
Alerts("hp-event-web",),
Alerts("hp-ezpzpass-views-matching_metrics",),
Alerts("hp_growth_partner-events",),
Alerts("hp_hurricane_events_vehicle_utilization",),
Alerts("hp_scream_transactions",),
Alerts("hp_supply_location-updated",),
Alerts("hp_supply_supply-offline",),
Alerts("hp_supply_supply-online",),
Alerts("hp_uberex_metrics",),
Alerts("invoice-gen_audit_trail",),
Alerts("kaizen_events",),
Alerts("man_in_the_muni_quality_matched",),
Alerts("man_in_the_muni_quality_unmatched",),
Alerts("mastermind_decide_trip_request_free_ride",),
Alerts("mastermind_v3_actions",),
Alerts("mobile_events",),
Alerts("money_fraud",),
Alerts("money_fraud_cyborg",),
Alerts("money_fraud_mastermind_promotions",),
Alerts("money_fraud_mastermind_signups",),
Alerts("money_fraud_sift_science",),
Alerts("nagios_notifications",),
Alerts("notifier_notification_logs",),
Alerts("onboarding_artemis_event",),
Alerts("p2_dashboard_xpert_survey_result",),
Alerts("p2_wechat_events",),
Alerts("p2_wechat_ids",),
Alerts("partner-onboarding_events_call_me",),
Alerts("sentinel_events_score",),
Alerts("sentinel_events_trip_request_features",),
Alerts("streamio_rtsearch",),
Alerts("territories_audit_territory",),
Alerts("tools-access",),
Alerts("toolshed_uberinternal_com-access",),
Alerts("uber_model_user_phone_verify",),
Alerts("uberchange_events",),
Alerts("uberex_metrics",),
Alerts("utunes_requested_tracks",),
Alerts("vault_audit",),
Alerts("zendesk_tickets_first_filed",),
Alerts("zendesk_tickets_first_reply",),
Alerts("zendesk_tickets_first_resolved",),
         ]


i = 0
part = 0
file_ptr = None
#have only 10 checks per file so that we don't time out
for alert in alertList:
     if(i%5 == 0):
           if(file_ptr!=None):
                 file_ptr.close()
           file_ptr = open("./thresholds/kloak_migrator_lag_alerts_part_"+str(part),"w")  
           part = part + 1
     alert.set_topic_alert(file_ptr)
     i = i+1
